# Generated by Django 5.2 on 2025-04-13 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_product_description_alter_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
